# Generated by Django 4.2.6 on 2024-01-28 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aircraft_model', models.CharField(max_length=50)),
                ('plane_ID', models.CharField(max_length=100)),
                ('seating_capacity', models.IntegerField()),
                ('manufacturer', models.CharField(choices=[('boeing', 'Boeing'), ('air bus', 'Air Bus'), ('bombardier', 'Bombardier'), ('lockheed martin', 'Lockheed Martin'), ('gulf stream', 'Gulf Stream')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airline_name', models.CharField(max_length=100)),
                ('contact_info', models.TextField(max_length=200)),
                ('airline_ID', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IATA_CODE', models.CharField(max_length=50)),
                ('airport_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FlightInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Flight_ID', models.CharField(max_length=100)),
                ('departure_date', models.DateField()),
                ('departure_time', models.TimeField()),
                ('arrival_date', models.DateField()),
                ('departure_location', models.CharField(max_length=100)),
                ('arrival_location', models.CharField(max_length=100)),
                ('flight_type', models.CharField(choices=[('business', 'Business'), ('economy', 'Economy'), ('vip', 'VIP')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_partner', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_ID', models.CharField(max_length=100)),
                ('Price', models.IntegerField()),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_ID', models.CharField(max_length=100)),
                ('seat_number', models.CharField(max_length=100)),
                ('booking_date', models.DateField()),
                ('flight_class', models.CharField(choices=[('class a', 'CLASS A'), ('class b', 'CLASS B'), ('class c', 'CLASS C')], max_length=100)),
                ('QRCODE', models.CharField(max_length=100)),
                ('booking_status', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ticket.payment')),
            ],
        ),
    ]
