# Generated by Django 4.2.6 on 2024-01-28 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticket',
            name='fligh_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.flightinfo'),
        ),
        migrations.AddField(
            model_name='partner',
            name='airline_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.airline'),
        ),
        migrations.AddField(
            model_name='partner',
            name='airport_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.airport'),
        ),
        migrations.AddField(
            model_name='flightinfo',
            name='plane_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.aircraft'),
        ),
        migrations.AddField(
            model_name='airport',
            name='partnary',
            field=models.ManyToManyField(blank=True, through='ticket.Partner', to='ticket.airline'),
        ),
        migrations.AddField(
            model_name='airline',
            name='partnary',
            field=models.ManyToManyField(blank=True, through='ticket.Partner', to='ticket.airport'),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='airline_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.airline'),
        ),
    ]
